### ISSUE TITLE
Sensor only giving a value of `inf`

### ISSUE THREAD

**Issue by eliasfrimanns** [EEEManchester/gazebo_radiation_plugin#13]
Hi,
I was trying the different test worlds to check if I got everything to work when I noticed that the sensor (`sensor_0`) was only returning the value `inf`. This value was invariant of position, orientation and number of sources (even none), and whether I'm checking through Gazebo or ROS. 
I'm running on Ubuntu 18.04, ROS Melodic, Gazebo 9, and the melodic-radmsg branch.

EDIT: Nothing is returned in Gazebo

**Comment by eliasfrimanns** [comment]
```
header: 
  seq: 147045
  stamp: 
    secs: 1719911126
    nsecs: 972295137
  frame_id: "sim_sensor"
value: inf
pose: 
  position: 
    x: 0.0
    y: 0.0
    z: 0.0
  orientation: 
    x: 0.0
    y: 0.0
    z: 0.0
    w: 1.0
type: ''
---

```
This is what is returned with the example given in the README after running
```
rostopic echo /radiation_sensor_plugin/sensor_0 
```
